In [11]:
import numpy as np

# n: number data
# c: number class
# d: number dimenstion of each data

n,c,d=10,3,5
w_init=np.random.rand(d,c)
x=np.random.rand(d,n)
y=np.random.randint(0,c,n)
print(w_init)
print(x)
print(y)

[[0.33682171 0.98659708 0.39294313]
 [0.10595842 0.19948139 0.71331797]
 [0.69545595 0.23968925 0.99941378]
 [0.55818752 0.94307326 0.11809977]
 [0.10102934 0.41550317 0.72046178]]
[[0.19562157 0.23103263 0.19862626 0.14678517 0.32661267 0.18436903
  0.83675039 0.87259774 0.95224698 0.79181254]
 [0.62295383 0.43510817 0.22861279 0.59914632 0.49193539 0.05844861
  0.91510933 0.24853965 0.31152189 0.39375734]
 [0.69059944 0.65524634 0.54016588 0.63284395 0.68391533 0.69083852
  0.427438   0.2686338  0.98978967 0.44761596]
 [0.72085227 0.91364045 0.38485199 0.80810384 0.56111783 0.08974443
  0.78464978 0.46065423 0.21694126 0.50764947]
 [0.89569828 0.49679212 0.270546   0.94296774 0.12057729 0.11304255
  0.29346789 0.44237591 0.05179247 0.59711318]]
[1 0 1 1 1 1 2 2 2 0]


In [12]:
#return loss value and grad
def svm_loss_navie(w,x,y,lamda):
    loss_value=0.0
    d,c,n=w.shape[0],w.shape[1],x.shape[0]
    grad_w=np.zeros_like(w)
    
    for i in range(n):
        x_i=x[:,i]
        score=x_i.dot(w)
        
        for j in range(c):
            if j==y[i]:
                continue
            
            magin=1-score[y[i]]+score[j]
            if magin>0:
                loss_value+=magin
                grad_w[:,j]+=x_i
                grad_w[:,y[i]]-=x_i
                
    
    loss_value/=n
    loss_value+=0.5*lamda*np.sum(w*w)
    grad_w/=n
    grad_w+=lamda*w
    return loss_value,grad_w
                          

In [13]:
import time 
t1=time.time()
(loss_value1,w_grad1)=svm_loss_navie(w_init,x,y,0)
#reg means regularization 
print("Loss value with reg=0:     ",loss_value1)
t2=time.time()
print("Time for excute svm without reg: %0.5fs"%(t2-t1))
(loss_value2,w_grad2)=svm_loss_navie(w_init,x,y,0.1)
print("Loss value with reg=0.1:   ",loss_value2)
t3=time.time()
print("Time for excute svm with reg=0.1:  %0.5fs"%(t3-t2))
#print(w_grad2)

Loss value with reg=0:      2.1201451082795835
Time for excute svm without reg: 0.00538s
Loss value with reg=0.1:    2.3830366257610947
Time for excute svm with reg=0.1:  0.00640s
